### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by nuriel77**
* Fixed link to ZMQ, was pointing to httpAPI
* Looks like webAPI and httpAPI are the same? Fixed

### CODE REVIEW

**Comment by IoTMOD** [comment]
It should be `WebAPI` because the plugin is called `WebAPI`, so you must pass this name to disable the plugin.
I suppose the confusion comes from the fact that the configuration options are called `httpAPI.*` :thinking:

**Comment by nuriel77** [comment]
I c, I thought I might be wrong.

But then WebAPI link was: `**Settings**: [link](Configuration#httpAPI)  ` that's why I got confused

**Comment by IoTMOD** [comment]
Yeah, it's confusing. But renaming the config option (from `httpAPI` to `webAPI`) would be a breaking change, so we should probably wait until the API will change anyway

**Comment by nuriel77** [comment]
Ok, hope its okay now. Fixed the ZMQ link

**Comment by IoTMOD** [comment]
Thank you :pray: 
But another thing (sorry just saw it now :sweat_smile:):
The formatting is broken, now:
image
Should be:
image

**Comment by nuriel77** [comment]
hmm strange. I viewed RTF.
I am using `vim` to edit and it automatically changed to:
```
 ## WebAPI

-**Status:** Enabled
-**Description:** Runs an API server to be able to interact with the node.
-**Settings**: [link](./Configuration#httpAPI)
+**Status:** Enabled
+**Description:** Runs an API server to be able to interact with the node.
+**Settings**: [link](Configuration#httpAPI)
 **How-To**: n.a.
```
Not really visible what

I'll leave it then :) Failed attempt to update md file 😂 

Anyway just the ZMQ needs fixing, change to:
`**Settings**: [link](./Configuration#ZMQ)`

**Comment by IoTMOD** [comment]
:smile: 
I'll update it, thanks anyway :+1:

**Pull request closed without merging**
